### ISSUE TITLE
Metrics Doc Page 

### ISSUE THREAD

**Issue by manistal** [Vipyr/taskobra#3]
- [ ] Data Model Diagram

![metricsdatamodel](https://user-images.githubusercontent.com/8151897/73986540-dd085480-490b-11ea-8a50-1f21e01ed22b.jpg)

- [ ] Implementation Overview 
    - PSUtil Python Lib
    - Sampling daemon

- [ ] Pruning concept

**Comment by tsmanner** [comment]
Need to add the final two sections on Pruning and the Python `psutil` library.
