### ISSUE TITLE
Contributing Doc Page

### ISSUE THREAD

**Issue by manistal** [Vipyr/taskobra#6]
- [ ]  How do I file a bug report?
    - Link to the issues page
    - Talk about good issue practices

- [ ]  How do I find something to work on? 
    - Talk about milestones and goals

- [ ]  Making a Contribution 
    - Pull requests and pull request templates

- [ ] CI/Passing CI 
    - Something about Unit Tests and shit

**Comment by tsmanner** [comment]
This won't render into the github page as html for some reason...
